### ISSUE TITLE
Rota para consulta de Equipamentos v1

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/gestao-ventiladores-backend#19]
# 1. Consulta um equipamento
Consutlar um equipamento baseado em:
```
method: GET
url: /api/equipamento?ordem_servico="string"
```

# 2. Consulta equipamentos por status
Inicialmente vamos consultar baseando-se no status

```
method: POST
url: /api/equipamentos/find

{
  "status": "string"
}
```

# 3. Consultar todos os equipamentos
Trazer todos os equipamentos sem distinção

```
method: GET
url: /api/equipamentos
```

**Comment by denisousa** [comment]
A funcionalidade "Consulta um equipamento" já existe por meio da rota: 
'/api/equipamento/<numero_ordem_servico>'

**Comment by denisousa** [comment]
A funcionalidade "Consultar todos os equipamentos", já existe com essa mesma rota que você colocou chicão.
