### ISSUE TITLE
Alterar rota de consulta de equipamento/find (Rotas v2)

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/gestao-ventiladores-backend#24]
# Otimizar consultas

## 1. Rota de consulta de um equipamento
Adicionar a rota a capacidade de consultar no banco os seguintes campos: _id, numero_odem_servico.

> Observação: A demanda é para estes dois campos, mas se for possível aceitar qualquer campo, economizará trabalhos futuros.

> Todas os parâmetros serão condicionados como AND e =

```
method: POST
url: /api/equipamentos/find
Content-Type: application/json

{
  "_id": "string",
  "numero_ordem_servico": "string",
}
```

## 2. Adiciona a capacidade na rota /find de trazer somente algusn campos do banco atravéz da chave $select$

````
method: POST
url: /api/equipamentos/find
Content-Type: application/json

{
  "$select$": ["campo1", "campo2", "...]
}
````

**Comment by lucasvieira123** [comment]
method: POST
url: /api/equipamentos/find
Content-Type: application/json

O **where** 'é um json que contém condicionais dos atributos. Nessa primeira versão, cada atributo será uma condição AND e = (ou seja, ainda não tem operadores >,>= , < etc );
Repare que também é reconhecido atributos internos (ex.: estado_de_conservacao que é interno da triagem e  descricao que é interno de acessorios e da triagem);
**select** é um json é onde deve ser passado os campos que devem ser retornados utilizando um array;
Se nao for passado o **select** , todos os campos serão retornados
Se nao for passado o **select** com um array vazio , todos os campos serão retornados

```
{ 
	"where":{
		"_id" :"5e9db0f4d4db101146ed8117",
		"status" : "diagnostico",
		"triagem": {
			"estado_de_conservacao":"Usado",
			"acessorios":{
				"descricao":"Traquéias",
				"quantidade":1
			}
		}
	},
	
	"select" : ["status","numero_ordem_servico"]

}
```
