### ISSUE TITLE
Rota para CRUD de ordem de compra

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/gestao-ventiladores-backend#31]
# Descrição
No sistem já existe uma impressão de ordem de compra, mas ela precisa ser registrada no banco para termos controle de estoque de itens solicitados para compra.

![image](https://user-images.githubusercontent.com/6399202/79778524-37ac2c80-830f-11ea-95e3-35aae99907e5.png)

## Atividades
- [x] Criar rota POST para cadastrar: `/api/ordem_compra`
- [x] Utilizar a mesma rota POST para atualizar, validando pelo _id (ordem_servico_view possue exemplo): `/api/ordem_compra`
- [x] Criar uma rota PUT para atualizar (sim, termos duas rotas): `/api/ordem_compra/<id>`
- [x] Criar rota DELETE para remover: : `/api/ordem_compra/<id>`
- [x] Criar rota GET que traz todos os campos: : `/api/ordem_compra`
- [x] Criar rota GET que traz somente 1 campo pelo id: `/api/ordem_compra/<id>`
- [x] Criar rota POST com /find para retornar por consulta json: `/api/ordem_compra/find`

## Rotas:
*  /api/ordem_compra
* /api/ordem_compra/find
* /api/ordem_compra/<id>

## Retorno
Retornar sempre e somente: 
```json
{
  "_id": "id"
}
```

Menos da deleção, que retornará:
```json
{
  "ok": true
}
```

### Definição para o salvar e atualizar:
* A rota deve ser um `POST` para `api/ordem_compra`.
* O número da ordem de compra deve ser gerado pelo backend na api e deve ser sequencial e com quatro dígitos. Ex: 0001, 0002, 0003...
* Deverá conter um array de Itens cujo os campos são os mesmo do Diagnóstico
* Deve-se validar se foi enviado algum item, do contrário retornar uma mensagem de erro:
```json
{
  "error": true,
  "message": "Não foram enviados itens suficientes para ordem de compra"
}
```

# JSON do modelo
```json
{
  "numero_ordem_compra": "string",
  "itens": ["array"]
}
```

**Comment by denisousa** [comment]
Tixico, não entendi essa demanda: 
Criar rota POST com /find para retornar por consulta json: /api/ordem_compra/find

No exemplo de ordem de servico eu entendo o retorno ser feito baseado no "status", mas aqui quem seria a referência, visto que só existem os campos: "numero_ordem_compra" e itens.
