### ISSUE TITLE
Criar funcionalidade de edição de OS

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/gestao-ventiladores-backend#38]

**Comment by denisousa** [comment]
A atualização da triagem está sendo feita da seguinte forma:

PUT - http://127.0.0.1:5000/api/ordem_servico/<id_documento>

### Exemplo - Alterando o valor de "estado_de_conservacao" da triagem
'''
{
  "triagem": {
    "estado_de_conservacao": "teste",
  }
}
'''

OBS-1: Sempre passar as chaves triagem ou diagnostico, se não, a API irá recusar a atualização.
OBS-2: Basta passar somente os campos que devem ser atualizados.

Ainda falta realizar mais testes :)
