### ISSUE TITLE
Criar API para importar as triagens já cadastradas

### ISSUE THREAD

**Issue by lucasvieira123** [EscolaDeSaudePublica/gestao-ventiladores-backend#7]
Já existem triagens já cadastradas pelo google forms, portanto a gente tem que pegar esses dados e  importar para o nosso banco de dados no mongo.
Não sei se deve ser uma funcionalidade de importação ou eu bastar ir no postman e faço um PUT

**Comment by oxechicao** [comment]
Mapear o csv através do link para importar os dados estruturados no banco.
Receber a URL no parâmetro get ou post.
https://docs.google.com/spreadsheets/d/e/2PACX-1vReGuRPHIq68zmQ-9iGBLxVKFGoa0FcC8OU5FbCkhcUmdMFoRkbrMyAV2ZYsbcOiE87kTlK6RKpo4h2/pub?output=csv

**Comment by oxechicao** [comment]
Ao importar os dados da planilha, atentar para as marcas e modelos
Aparentemente não tem fabricante na planilha, então a marca será tratada como fabricante:

Assim, efetuar as condições abaixo para atualizar a collection de fabricante a partir da planilha

A cada inserção irá se verificar no banco se existe o fabricando definido.
Se não existir: inserir

Se exitir fabricante no banco:
Verificar se a marca está inserida dentro do fabricante:
Se não, inserir

Se existir a marca dentro do fabricante
Inserir o modelo dentro da marca

A collection fabricante ficará assim
```json
{
  "fabricante": "string",
  "marcas": [
     {
         "marca": "string",
         "modelos": [
              "string",
              "string",
              "..."
          ]
      },
      "..."
  ]
}
```
