### ISSUE TITLE
RECRIAR rota GET da Ordem de Serviço aos moldes da v2

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/gestao-ventiladores-backend#72]
# Objetivo

**Eu como** como usuário da API  
**Quero** efetuar consultas de ordens de serviços através da v2  
**Para que** eu possa consultar as rotas na nova arquitetura

# Contexto

As rotas das ordens de serviços foram feitas em uma forma não convencional criadas de acordo com a necessidade.  
Para se alinhar à nova arquitetura, uma refatoração para a v2 da API é necessária. 

# Fora de Contexto

Criar rotas de POST, PUT, PATCH, DELETE

# Dentro do escopo

Adicionar campo deleted_at à collection de Ordem de Serviço

# Critérios de aceitação

- [x] **Dado que** desejo consultar todos as ordens de serviço não deletadas  
**Quando** efetuar uma consulta na rota `v2/service_orders`  
**Então** retornar todos as ordens de serviços que não foram removidas (aquelas que não posuem `deleted_at`)

- [x] **Dado que** desejo consultar todos as ordens de serviço inclusive as deletadas  
**Quando** efetuar uma consulta na rota `v2/service_orders?deleted=true`  
**Então** retornar todos as ordens de serviços inclusive as removidas (as que possuem `deleted_at` também)

# Observações

Arquitetura de referência #49

## JSON de modelo da ordem de serviço

```json
{
    "equipamento_id": "ObjectId do equipamento",
    "numero_ordem_servico": "string com 4 caracteres, sendo 0 a esquerda",
    "created_at": "$date",
    "updated_at": "$date",
    "status": "string",
    "triagem": {
        "estado_de_conservacao": "string",
        "foto_antes_limpeza": "string",
        "foto_apos_limpeza": "",
        "acessorios": [
            {
                "item_id": "ObjectId do item",
                "estado_de_conservacao": "string",
                "quantidade": "",
                "acompanha": ""
            },
            "..."
        ]
    },
    "diagnostico": {
        "resultado_tecnico": "string",
        "demanda_servicos": "string",
        "observacoes": "string",
        "itens": [
            {
                "item_id": "ObjectId do item",
                "quantidade": "number"
            },
            "..."
        ]
    },
    "calibragem": {
        "status": "string"
    }
}
```

**Comment by sarahraqueld** [comment]
Lembrete: Fazer dev huddle sobre a nossa abordagem de testes nesse card.
